FROM rancher/fluentd:v0.1.19
MAINTAINER chenbilong <chenbilong@outlook.com>
RUN fluent-gem install fluent-plugin-forest &&\
    fluent-gem install fluent-plugin-record-reformer \
    fluent-gem install fluentd-plugin-detect-exceptions